// <auto-generated />
using System;
using EYEAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EYEAPI.Migrations
{
    [DbContext(typeof(EyeContext))]
    [Migration("20251022163449_asdvsdcCACACS")]
    partial class asdvsdcCACACS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EYEAPI.Models.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("MaximumValue")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlarmId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandledFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("MachineId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MetaDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SublocationId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetaDataId")
                        .IsUnique()
                        .HasFilter("[MetaDataId] IS NOT NULL");

                    b.HasIndex("SublocationId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.MachineMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("TotalMemory")
                        .HasColumnType("int");

                    b.Property<int>("TotalStorage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MachineMetaData");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Sublocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Sublocations");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Alarm", b =>
                {
                    b.HasOne("EYEAPI.Models.Entities.Machine", "Machine")
                        .WithMany("Alarms")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.EventLog", b =>
                {
                    b.HasOne("EYEAPI.Models.Entities.Alarm", "Alarm")
                        .WithMany("EventLogs")
                        .HasForeignKey("AlarmId");

                    b.HasOne("EYEAPI.Models.Entities.Machine", "Machine")
                        .WithMany("EventLogs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Machine", b =>
                {
                    b.HasOne("EYEAPI.Models.Entities.MachineMetaData", "MetaData")
                        .WithOne("Machine")
                        .HasForeignKey("EYEAPI.Models.Entities.Machine", "MetaDataId");

                    b.HasOne("EYEAPI.Models.Entities.Sublocation", "Sublocation")
                        .WithMany("Machines")
                        .HasForeignKey("SublocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaData");

                    b.Navigation("Sublocation");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Sublocation", b =>
                {
                    b.HasOne("EYEAPI.Models.Entities.Location", "Location")
                        .WithMany("Sublocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Alarm", b =>
                {
                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Location", b =>
                {
                    b.Navigation("Sublocations");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Machine", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.MachineMetaData", b =>
                {
                    b.Navigation("Machine")
                        .IsRequired();
                });

            modelBuilder.Entity("EYEAPI.Models.Entities.Sublocation", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
